### ISSUE TITLE
A bug in padding mode in Debayer3x3  module?

### ISSUE THREAD

**Issue by QiuJueqin** [cheind/pytorch-debayer#3]
Hi, should the mode of padding in Debayer3x3 be 'reflect' instead of 'replicate'?

https://github.com/cheind/pytorch-debayer/blob/9c1d19406cdf50b8ed43938af11237634cbda427/debayer/debayer.py#L86

**Comment by cheind** [comment]
Yes that could be an issue. Please note that the variants implemented are considered basic. There are much more sophisticated debayering methods out there.

**Comment by cheind** [comment]
though about it again: consider a gradient of black towards white at an image edge. then reflect would actually make an edge at that point, while replicate might just repeat white - which seems to be more reasonable to me.

**Comment by cheind** [comment]
I believe I was to quick with my answer. I believe you are correct and that reflective pattern should be used, since we are not dealing with full color images but bayer inputs. In which case a reflective pattern would correctly reproduce the structure of the bayer filter.

**Comment by cheind** [comment]
When padding is not reflective, the following test function fails to reconstruct simple monochromatic images.

https://github.com/cheind/pytorch-debayer/blob/4e3d019b9b30be94ad3e19a9d634d4a27b5a9b17/tests/test_debayer.py

Which verifies that reflection padding is the way to go.
