### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by ycjing** [cheind/pytorch-debayer#4]
Hi @cheind 

Thank you so much for this great work! I would like to cite your great work in my paper submission. Is any of your publications that uses this great debayer work?

Thank you! Wish you all the best!

Best,
Yongcheng

**Comment by cheind** [comment]
Hey,

the method is not described in detail in any publiction, but is used in this work
```
@inproceedings{robotpose_etfa2019_cheind,
    author={Christoph {Heindl} and Sebastian Zambal and Josef {Scharinger}},
    title={Learning to Predict Robot Keypoints Using Artificially Generated Images},
    booktitle={24th IEEE International Conference on Emerging Technologies and Factory Automation (ETFA)},    
    year={2019},
    publisher={IEEE},
    volume={},
    number={},
    pages={1536-1539},
    doi={10.1109/ETFA.2019.8868243},
    isbn={978-1-7281-0303-7},
    ISSN={1946-0740},
}
```

**Comment by ycjing** [comment]
Hi @cheind 

I appreciate it. Will cite this work in my paper submission. Thank you for the nice code again!

Best,
Yongcheng

**Comment by cheind** [comment]
Thanks for the citation!
