### ISSUE TITLE
RGB or BGR?

### ISSUE THREAD

**Issue by Ryanshuai** [cheind/pytorch-debayer#6]
Hi Christoph,

Thanks for your work. This project helped me a lot.
I just want to make sure:
Is there any possibility the channel(RGB) of the output of the debayer is reversed?
I tested it with "from colour_demosaicing.bayer.demosaicing import bilinear, malvar2004, menon2007".
The output of colour_demosaicing and debayer is in different rgb (bgr) orders.

Thanks again
Shuai Yan

**Comment by cheind** [comment]
Hey,

According to my docs, the output channel order of pytorch-debayer should be RGB. Are you saying that this is not the case? In case there is not a bug in this library, I suspect that a BGR order can occur if you choose the wrong `Layout` when performing debayering. 

https://github.com/cheind/pytorch-debayer/blob/a910a9e3839c5947c7659c9e0114562b6e2b253e/debayer/layouts.py#L4

The Layout refers to the upper 2x2 block of the bayer image, as explained here
https://github.com/cheind/pytorch-debayer#bayer-layouts

**Comment by Ryanshuai** [comment]
Hi Christoph,

Thanks for the guide, it is something wrong with the Layout.
Thank you for your time.
